// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    2: typeof import('./components/SelfIntroduction copy 2.vue')['default']
    copy: typeof import('./components/SelfIntroduction copy.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Divider: typeof import('./components/Divider.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Operation: typeof import('./components/resume/Operation.vue')['default']
    PersonalSkills: typeof import('./components/resume/PersonalSkills.vue')['default']
    ProjectExperience: typeof import('./components/resume/ProjectExperience.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    School: typeof import('./components/resume/School.vue')['default']
    SelfIntroduction: typeof import('./components/resume/SelfIntroduction.vue')['default']
    SelfProfile: typeof import('./components/resume/SelfProfile.vue')['default']
    Sohcol: typeof import('./components/Sohcol.vue')['default']
    WorkExperience: typeof import('./components/resume/WorkExperience.vue')['default']
  }
}
