// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Collapse: typeof import('./components/resume/Collapse.vue')['default']
    Divider: typeof import('./components/resume/Divider.vue')['default']
    Drawer: typeof import('./components/resume/Drawer.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HeadImgSetting: typeof import('./components/resume/setting/HeadImgSetting.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    ImportSetting: typeof import('./components/resume/setting/ImportSetting.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    OpenSourceProject: typeof import('./components/resume/OpenSourceProject.vue')['default']
    OpenSourceProjectSetting: typeof import('./components/resume/setting/OpenSourceProjectSetting.vue')['default']
    Operation: typeof import('./components/resume/Operation.vue')['default']
    PerjectSetting: typeof import('./components/resume/setting/PerjectSetting.vue')['default']
    PersonalSkills: typeof import('./components/resume/PersonalSkills.vue')['default']
    ProjectExperience: typeof import('./components/resume/ProjectExperience.vue')['default']
    README: typeof import('./components/README.md')['default']
    Resume: typeof import('./components/resume/Resume.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    School: typeof import('./components/resume/School.vue')['default']
    SchoolSetting: typeof import('./components/resume/setting/SchoolSetting.vue')['default']
    SelectTheme: typeof import('./components/SelectTheme/SelectTheme.vue')['default']
    SelfInfoSetting: typeof import('./components/resume/setting/SelfInfoSetting.vue')['default']
    SelfIntroduction: typeof import('./components/resume/SelfIntroduction.vue')['default']
    SelfProfile: typeof import('./components/resume/SelfProfile.vue')['default']
    SelfSetting: typeof import('./components/resume/setting/SelfSetting.vue')['default']
    Skeleton: typeof import('./components/Skeleton.vue')['default']
    SkillsSetting: typeof import('./components/resume/setting/SkillsSetting.vue')['default']
    Template_1: typeof import('./components/resume/theme/Template_1.vue')['default']
    Template_2: typeof import('./components/resume/theme/Template_2.vue')['default']
    Template_3: typeof import('./components/resume/theme/Template_3.vue')['default']
    ThemeSetting: typeof import('./components/ThemeSetting.vue')['default']
    WorkExperience: typeof import('./components/resume/WorkExperience.vue')['default']
    WorkExperienceSetting: typeof import('./components/resume/setting/WorkExperienceSetting.vue')['default']
  }
}
